### ISSUE TITLE
Не устанавливается mdk4 на Fedora

### ISSUE THREAD

**Issue by Kson-arch** [aircrack-ng/mdk4#101]
Всем привет, прошу помогите, у меня Fedora и появилась проблема с установкой mdk4
при моём вводе 'make' выводит:
make -C src clean
make[1]: вход в каталог «/root/airgeddon/mdk4/src»
../common.mak:100: *** Cannot find development files for any supported version of libnl. install either libnl1 or libnl3..  Останов.
make[1]: выход из каталога «/root/airgeddon/mdk4/src»
make: *** [Makefile:19: clean] Ошибка 2
Кто подскажет, что делать, буду очень благодарен

**Comment by aircrack-ng** [comment]
`Cannot find development files for any supported version of libnl. install either libnl1 or libnl3`

Install libnl development package
