### ISSUE TITLE
CTS flood not working as intended

### ISSUE THREAD

**Issue by TIISR** [aircrack-ng/mdk4#108]
Hi and many thanks for this great software!

I have noticed an issue that I would happily patch but unfortunately I do not have yet a full solution (other than SDR + OpenWiFi) as I have yet to find a way implement RTS/CTS attacks on recent hardware that all seem to offload Control frames or at least the Duration field thereof:

Running `mdk wlan0 f -s c -m d` is supposed to create a flood of CTS frames with random (flags and) duration and there is nothing wrong with how [create_cts()](https://github.com/aircrack-ng/mdk4/blob/c6a35994b2f0d87d79ce9a072b84a486775d8ee4/src/packet.c#L284) is implemented, it's just that when injecting with one card and sniffing with another to see what was actually transmitted, you will see that the duration field gets overwritten.

This due to one or both (depending on the driver) of two reasons:

1. Setting the RA to ff:ff:ff:ff:ff:ff makes it a multicast MAC and this gets Duration forced to 0 as you can see for example in the Linux kernel's mac80211 code with [ieee80211_tx_h_calculate_duration()](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/mac80211/tx.c?h=v6.4#n1110) flagging it as a group_addr and [ieee80211_duration()](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/net/mac80211/tx.c?h=v6.4#n119) correspondingly forcing Duration to 0.
2. Even with patching the kernel to avoid the previous point (successfully as confirmed with usbmon sniffing), none of the many PCIe/USB WiFi cards with different drivers and chipsets (even tried ESP8266 and ESP32) t
<img width="918" alt="Duration is 0" src="https://github.com/aircrack-ng/mdk4/assets/124567646/91434016-a845-4a15-a4fa-10ab3ed99bb0">
hat I have tried let me send CTS (or RTS) frames the way I want: they all either overwrite the Duration with a tiny value such as 36 or 44 TU, or outright drop the frame.

If anyone manages to make it work please let me know! I have a bit of hope with older Intel (ipw2x00) cards but it's looking more and more like I'll have to source a PCMCIA adapter to be able to reenact the good old days :)

**Comment by aircrack-ng** [comment]
Not all adapters support injecting control frames, and it looks like ipw2x00 adapters are one of them. Get yourself an AWUS036NHA.

**Comment by TIISR** [comment]
lol?!

NHA is one of the "none of the many PCIe/USB WiFi cards with different drivers and chipsets" including ACH, ACHM, ACM, AXML and even more of the Alfa catalogue (NFM, Tube-UNA, etc).

If you took a second to read what I took much longer to write, I mentioned older cards as hope, not what I have tested and verified to not work!

Does it work on your NHA? I bet you it does not.

**Comment by aircrack-ng** [comment]
I read what you wrote, and you didn't mention any particular wifi adapter other than the old Intel ones (and I know old Intel adapters are bad at injecting).

I don't know what you mean by "none of the many PCIe/USB WiFi cards with different drivers and chipsets". Could you elaborate.


I haven't tested your particular scenario, but I know the NHA adapter (using `ath9k_htc`) can inject CTS. I haven't dug into the drivers but I'm willing to bet that it's a firmware limitation, so driver patching would be pointless (feel free to correct me if I'm wrong).

I can tell you that the ACM does not, and I'm guessing so do the ACHM, AXM and AXM/AXML as they all have a mediatek chipset. I'm willing to bet that the ACH, with its realtek chipset also doesn't.
