### ISSUE TITLE
an whitelist station Option !

### ISSUE THREAD

**Issue by minanagehsalalma** [aircrack-ng/mdk4#26]
@E7mer
an whitelist station Option would be very useful ...
just like mdk4 d -B 20-A1-BF-1F-8C-FE -WS FE-60-3C-E1-1E-71
that disconnects all clients but not this white listed one ...........
as this well be helpful while doing tests ..

**Comment by E7mer** [comment]
@minanagehsalalma Hi, This option has been added，  mdk4 d -B 20-A1-BF-1F-8C-FE -W FE-60-3C-E1-1E-71

**Comment by PoloB12** [comment]
I don't seem to get this working with option -b  :

mdk4 $mdk_interface d -b target_ap_macs.txt -c $mdk_channel -W $ignored_station_mac

Also other ap's and clients get disconnected then, which doesn't happen when I omit the -W option.
