### ISSUE TITLE
Mode d dont work with key -w

### ISSUE THREAD

**Issue by vahavahidov** [aircrack-ng/mdk4#33]
mdk4 mon0 d -w white = nothing happened

**Comment by adde88** [comment]
I've also noticed this. I'm compiling for my Wifi Pineapple (OpenWRT).
I tried digging into it and the issue started happening with commit: c32512aed60a960613fb71b5e04b303db79d7982 from @E7mer.
Every commit after that one has this issue, so i have to use the earlier commit to get that attack working properly.
I'll try to look more into it, and see if i can find exactly what's causing the issue.

Normally when using **-w**we get the output into the terminal of all the MAC addresses that are being attacked, but after that commit nothing happens. It's just silent, forever.

**Comment by E7mer** [comment]
Hi, bugs have been fixed.
