### ISSUE TITLE
mdk4 d -S or -B not limited to device specified

### ISSUE THREAD

**Issue by alphafox02** [aircrack-ng/mdk4#35]
Pulled down latest and built for Openwrt. Testing with an Alfa card specifying a specific BSSID with the d attack using -B and also tried a specific station MAC with -S. The attack starts and is not limited to just the devices specified, instead it starts attacking other devices.

By reading the description I thought it would only attack the device listed in the command line. Is this not the expected behavior?

**Comment by alphafox02** [comment]
Using the blacklist from file method works.

**Comment by E7mer** [comment]
Testing with this command，
./mdk4 wlan0 d -B 00:11:XX:00:XX:12 -S F8:XX:71:72:A8:XX
it works， only attack the specific station  F8:XX:71:72:A8:XX

alphafox02 <notifications@github.com> 于2019年5月17日周五 下午1:21写道：

**Comment by alphafox02** [comment]
Thank you. I was doing it wrong.

**Comment by Heporis** [comment]
@alphafox02 
Hi, how to build mdk4 for OpenWrt?
