### ISSUE TITLE
mdk4 won't deauth using blacklist -b option

### ISSUE THREAD

**Issue by usama7628674** [aircrack-ng/mdk4#37]
@E7mer @aircrack-ng @samueloph 
So the following command I used
`mdk4 wlan0mon d -c 1 -b dis.txt`

If I don't use `-b` it deauthenticates fine but using -b blacklist won't deauth AP however mdk3 works fine with the above command. 

Tested on `Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-5kali1 (2019-06-20) x86_64 GNU/Linux`

**Comment by usama7628674** [comment]
Reverting back to ` 879eb05` fixed this issue

**Comment by E7mer** [comment]
Bugs have been fixed.
