### ISSUE TITLE
Help: How to attack one Station mac without BSSID/ESSID?

### ISSUE THREAD

**Issue by wuguzaliang** [aircrack-ng/mdk4#39]
Hi, I am trying and using mdk4. I want to attack one station mac with Deauthentication and  Disassociation mode. I don't know how to. I tried to run "mdk4 wifi1 d -S xx:xx:xx:xx:xx:xx" and it didn't work. Could you please kindly give me some instructions? Thx

**Comment by NuKESec** [comment]
use https://github.com/DanMcInerney/wifijammer

MDK3 and MDK4 are weak as fucking shit. doesn't use the blacklist, doesn't deauth properly, and doesn't take a network down for shit

**Comment by wuguzaliang** [comment]
@NuKESec , It's gr8, Thx. your jammer works better.
