### ISSUE TITLE
errors while make：

### ISSUE THREAD

**Issue by zhuzhihao15** [aircrack-ng/mdk4#47]
In file included from /usr/include/linux/wireless.h:74,
                 from channelhopper.c:13:
/usr/include/linux/if.h:226:8: error: redefinition of ‘struct ifconf’
 struct ifconf  {
        ^~~~~~
In file included from channelhopper.c:4:
/usr/include/net/if.h:176:8: note: originally defined here
 struct ifconf
        ^~~~~~
channelhopper.c:48:26: warning: initialization of ‘pthread_t’ {aka ‘long unsigned int’} from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
 pthread_t chan_sniffer = NULL;
                          ^~~~
channelhopper.c: In function ‘error_handler’:
channelhopper.c:155:46: warning: unused parameter ‘nla’ [-Wunused-parameter]
 static int error_handler(struct sockaddr_nl *nla, struct nlmsgerr *err,
                          ~~~~~~~~~~~~~~~~~~~~^~~
channelhopper.c: In function ‘finish_handler’:
channelhopper.c:163:42: warning: unused parameter ‘msg’ [-Wunused-parameter]
 static int finish_handler(struct nl_msg *msg, void *arg)
                           ~~~~~~~~~~~~~~~^~~
channelhopper.c: In function ‘ack_handler’:
channelhopper.c:170:39: warning: unused parameter ‘msg’ [-Wunused-parameter]
 static int ack_handler(struct nl_msg *msg, void *arg)
                        ~~~~~~~~~~~~~~~^~~
channelhopper.c: In function ‘valid_handler’:
channelhopper.c:186:45: warning: unused parameter ‘arg’ [-Wunused-parameter]
 int valid_handler(struct nl_msg *msg, void *arg)
                                       ~~~~~~^~~
channelhopper.c: In function ‘handle_channels’:
channelhopper.c:328:50: warning: unused parameter ‘state’ [-Wunused-parameter]
 static int handle_channels(struct nl80211_state *state, struct nl_msg *msg)
                            ~~~~~~~~~~~~~~~~~~~~~~^~~~~
At top level:
channelhopper.c:240:14: warning: ‘dfs_state_name’ defined but not used [-Wunused-function]
 static char *dfs_state_name(enum nl80211_dfs_state state)
              ^~~~~~~~~~~~~~
make[1]: *** [channelhopper.o] Error 1
make[1]: Leaving directory `/home/mdk4/src'
make: *** [all] Error 2


Ubuntu14.04
gcc 8.3.0

**Comment by aircrack-ng** [comment]
Ubuntu 14.04 isn't supported anymore, and there is probably something wrong on your system; it compiles just fine on Kali, Ubuntu 16.04, and 18.04. You can always try deleting your mdk4 copy and getting it again, sometimes local copies may get corrupt.

Feel free to reopen this bug if it happens with any currently supported distribution, and please use github markdown formatting for the output of make.
