### ISSUE TITLE
"b attack" : what happen with -w option ?

### ISSUE THREAD

**Issue by Bob36180** [aircrack-ng/mdk4#5]
Hello,
I actually am working on this new mdk3 version. I'm interested by the "b attack" of this program, which allows to create fake APs... Let us imagine that I type this command 
`mdk4 wlan0 b -n Livebox_123 -t 0 -w a -h -c 3`
... what happens when someone try to connect to Livebox_123 ?? If the victim insert a random WPA key thinking it is his own box (Rogue AP principle), is it possible to get the entered key ??
Thanks in advance.

**Comment by E7mer** [comment]
You can capture the packets with wireshark and take a look  at
them,  counld't get the entered key

2018-06-14 22:23 GMT+08:00 Bob36180 <notifications@github.com>:
