### ISSUE TITLE
 libnl1 or libnl3.

### ISSUE THREAD

**Issue by wuerjiu529** [aircrack-ng/mdk4#6]
make -C src clean
make[1]: Entering directory '/home/pi/mdk4/src'
../common.mak:100: *** Cannot find development files for any supported version o            f libnl. install either libnl1 or libnl3.。 停止。
make[1]: Leaving directory '/home/pi/mdk4/src'
Makefile:18: recipe for target 'clean' failed
make: *** [clean] Error 2

**Comment by E7mer** [comment]
try to install libnl:
apt-get install libnl-3-dev libnl-genl-3-dev
