### ISSUE TITLE
Mdk4 802.11 AC -c not work

### ISSUE THREAD

**Issue by Zanzaux** [aircrack-ng/mdk4#60]

**Comment by slt90** [comment]
> mdk4 wlan1 d -b black.txt -c 160,149
> 
> Disconnecting00:15:6D:FC:2A:00 from 00:15:1D:C2:24:44 on channel 149
> Packets sent: 1 - Speed: 1 packets/sec
> Disconnecting 50:0F:F5:E7:2B:70 from 00:15:1D:C2:24:44 on channel 149
> Packets sent: 9 - Speed: 8 packets/sec
> Disconnecting 00:15:6D:FC:2A:00 from 00:15:1D:C2:24:44 on channel 149
> Packets sent: 29 - Speed: 20 packets/sec
> Disconnecting 00:15:6D:FC:2A:00 from00:15:1D:C2:24:44 on channel 160 (this is at Ch 149 )
> Packets sent: 37 - Speed: 8 packets/sec
> 
> the mac with channel 160 is completely excluded (78: 8A: 20: D0: A4: CC) i believe there are problems with skipping 5GHZ channels.

**Comment by Mister-X-** [comment]
Is channel 160 allowed? Run `iw list` and post output.
Did you kill network managers prior to running it?

Please format the bug report

**Comment by slt90** [comment]
through a .SH file I execute these commands for mode monito
I restart service NetworkManager start
because it is a remote location, I also tried without service NetworkManager start but it is the same

airmon-ng check kill
sudo ip link set wlan1 down
iw dev wlan1 set type monitor
sudo ip link set wlan1 up
sudo iw wlan1 set txpower fixed 3000
service NetworkManager start 
iw wlan1 info


` iw list                                                                                                                                    
Wiphy phy1                                                                                                                                                 
        wiphy index: 1                                                                                                                                     
        max # scan SSIDs: 9                                                                                                                                
        max scan IEs length: 2304 bytes                                                                                                                    
        max # sched scan SSIDs: 0                                                                                                                          
        max # match sets: 0                                                                                                                                
        max # scan plans: 1                                                                                                                                
        max scan plan interval: -1                                                                                                                         
        max scan plan iterations: 0                                                                                                                        
        Retry short limit: 7                                                                                                                               
        Retry long limit: 4                                                                                                                                
        Coverage class: 0 (up to 0m)                                                                                                                       
        Supported Ciphers:                                                                                                                                 
                * WEP40 (00-0f-ac:1)                                                                                                                       
                * WEP104 (00-0f-ac:5)                                                                                                                      
                * TKIP (00-0f-ac:2)                                                                                                                        
                * CCMP-128 (00-0f-ac:4)                                                                                                                    
                * CMAC (00-0f-ac:6)                                                                                                                        
        Available Antennas: TX 0x2 RX 0x2                                                                                                                  
        Supported interface modes:                                                                                                                         
                 * IBSS                                                                                                                                    
                 * managed                                                                                                                                 
                 * AP                                                                                                                                      
                 * monitor                                                                                                                                 
        Band 1:                                                                                                                                            
                Capabilities: 0x1a72                                                                                                                       
                        HT20/HT40                                                                                                                          
                        Static SM Power Save                                                                                                               
                        RX Greenfield                                                                                                                      
                        RX HT20 SGI                                                                                                                        
                        RX HT40 SGI                                                                                                                        
                        RX STBC 2-streams                                                                                                                  
                        Max AMSDU length: 7935 bytes                                                                                                       
                        DSSS/CCK HT40                                                                                                                      
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)                                                                                      
                Minimum RX AMPDU time spacing: 16 usec (0x07)                                                                                              
                HT Max RX data rate: 300 Mbps                                                                                                              
                HT TX/RX MCS rate indexes supported: 0-15                                                                                                  
                Bitrates (non-HT):                                                                                                                         
                        * 1.0 Mbps                                                                                                                         
                        * 2.0 Mbps                                                                                                                         
                        * 5.5 Mbps                                                                                                                         
                        * 11.0 Mbps                                                                                                                        
                        * 6.0 Mbps                                                                                                                         
                        * 9.0 Mbps                                                                                                                         
                        * 12.0 Mbps                                                                                                                        
                        * 18.0 Mbps                                                                                                                        
                        * 24.0 Mbps                                                                                                                        
                        * 36.0 Mbps                                                                                                                        
                        * 48.0 Mbps                                                                                                                        
                        * 54.0 Mbps                                                                                                                        
                Frequencies:                                                                                                                               
                        * 2412 MHz [1] (20.0 dBm)                                                                                                          
                        * 2417 MHz [2] (20.0 dBm)                                                                                                          
                        * 2422 MHz [3] (20.0 dBm)                                                                                                          
                        * 2427 MHz [4] (20.0 dBm)                                                                                                          
                        * 2432 MHz [5] (20.0 dBm)                                                                                                          
                        * 2437 MHz [6] (20.0 dBm)                                                                                                          
                        * 2442 MHz [7] (20.0 dBm)                                                                                                          
                        * 2447 MHz [8] (20.0 dBm)                                                                                                          
                        * 2452 MHz [9] (20.0 dBm)                                                                                                          
                        * 2457 MHz [10] (20.0 dBm)                                                                                                         
                        * 2462 MHz [11] (20.0 dBm)                                                                                                         
                        * 2467 MHz [12] (20.0 dBm)                                                                                                         
                        * 2472 MHz [13] (20.0 dBm)                                                                                                         
                        * 2484 MHz [14] (20.0 dBm)                                                                                                         
        Band 2:                                                                                                                                            
                Capabilities: 0x1a72                                                                                                                       
                        HT20/HT40                                                                                                                          
                        Static SM Power Save                                                                                                               
                        RX Greenfield                                                                                                                      
                        RX HT20 SGI                                                                                                                        
                        RX HT40 SGI                                                                                                                        
                        RX STBC 2-streams                                                                                                                  
                        Max AMSDU length: 7935 bytes                                                                                                       
                        DSSS/CCK HT40                                                                                                                      
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)                                                                                      
                Minimum RX AMPDU time spacing: 16 usec (0x07)                                                                                              
                HT Max RX data rate: 300 Mbps                                                                                                              
                HT TX/RX MCS rate indexes supported: 0-15                                                                                                  
                VHT Capabilities (0x03c031a2):                                                                                                             
                        Max MPDU length: 11454                                                                                                             
                        Supported Channel Width: neither 160 nor 80+80                                                                                     
                        short GI (80 MHz)                                                                                                                  
                        TX STBC                                                                                                                            
                        SU Beamformee                                                                                                                      
                        +HTC-VHT                                                                                                                           
                VHT RX MCS set:                                                                                                                            
                        1 streams: MCS 0-9                                                                                                                 
                        2 streams: MCS 0-9                                                                                                                 
                        3 streams: not supported                                                                                                           
                        4 streams: not supported                                                                                                           
                        5 streams: not supported                                                                                                           
                        6 streams: not supported                                                                                                           
                        7 streams: not supported                                                                                                           
                        8 streams: not supported                                                                                                           
                VHT RX highest supported: 867 Mbps                                                                                                         
                VHT TX MCS set:                                                                                                                            
                        1 streams: MCS 0-9                                                                                                                 
                        2 streams: MCS 0-9                                                                                                                 
                        3 streams: not supported                                                                                                           
                        4 streams: not supported                                                                                                           
                        5 streams: not supported                                                                                                           
                        6 streams: not supported                                                                                                           
                        7 streams: not supported                                                                                                           
                        8 streams: not supported                                                                                                           
                VHT TX highest supported: 867 Mbps                                                                                                         
                Bitrates (non-HT):                                                                                                                         
                        * 6.0 Mbps                                                                                                                         
                        * 9.0 Mbps                                                                                                                         
                        * 12.0 Mbps                                                                                                                        
                        * 18.0 Mbps                                                                                                                        
                        * 24.0 Mbps                                                                                                                        
                        * 36.0 Mbps                                                                                                                        
                        * 48.0 Mbps                                                                                                                        
                        * 54.0 Mbps                                                                                                                        
                Frequencies:                                                                                                                               
                        * 5180 MHz [36] (30.0 dBm)                                                                                                         
                        * 5200 MHz [40] (30.0 dBm)                                                                                                         
                        * 5220 MHz [44] (30.0 dBm)                                                                                                         
                        * 5240 MHz [48] (30.0 dBm)                                                                                                         
                        * 5260 MHz [52] (30.0 dBm)                                                                                                         
                        * 5280 MHz [56] (30.0 dBm)                                                                                                         
                        * 5300 MHz [60] (30.0 dBm)                                                                                                         
                        * 5320 MHz [64] (30.0 dBm)                                                                                                         
                        * 5500 MHz [100] (30.0 dBm)                                                                                                        
                        * 5520 MHz [104] (30.0 dBm)                                                                                                        
                        * 5540 MHz [108] (30.0 dBm)                                                                                                        
                        * 5560 MHz [112] (30.0 dBm)                                                                                                        
                        * 5580 MHz [116] (30.0 dBm)                                                                                                        
                        * 5600 MHz [120] (30.0 dBm)                                                                                                        
                        * 5620 MHz [124] (30.0 dBm)                                                                                                        
                        * 5640 MHz [128] (30.0 dBm)                                                                                                        
                        * 5660 MHz [132] (30.0 dBm)                                                                                                        
                        * 5680 MHz [136] (30.0 dBm)                                                                                                        
                        * 5700 MHz [140] (30.0 dBm)                                                                                                        
                        * 5720 MHz [144] (30.0 dBm)                                                                                                        
                        * 5745 MHz [149] (30.0 dBm)                                                                                                        
                        * 5765 MHz [153] (30.0 dBm)                                                                                                        
                        * 5785 MHz [157] (30.0 dBm)                                                                                                        
                        * 5805 MHz [161] (30.0 dBm)                                                                                                        
                        * 5825 MHz [165] (30.0 dBm)                                                                                                        
                        * 5845 MHz [169] (30.0 dBm)                                                                                                        
                        * 5865 MHz [173] (30.0 dBm)                                                                                                        
                        * 5885 MHz [177] (30.0 dBm)                                                                                                        
        Supported commands:                                                                                                                                
                 * new_interface                                                                                                                           
                 * set_interface                                                                                                                           
                 * new_key                                                                                                                                 
                 * start_ap                                                                                                                                
                 * new_station                                                                                                                             
                 * set_bss                                                                                                                                 
                 * join_ibss                                                                                                                               
                 * set_pmksa                                                                                                                               
                 * del_pmksa                                                                                                                               
                 * flush_pmksa                                                                                                                             
                 * remain_on_channel                                                                                                                       
                 * frame                                                                                                                                   
                 * set_wiphy_netns                                                                                                                         
                 * set_channel                                                                                                                             
                 * connect                                                                                                                                 
                 * disconnect                                                                                                                              
        Supported TX frame types:                                                                                                                          
                 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0                                                   
                 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0                                                
                 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0                                                     
                 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0                                                
                 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0                                             
                 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0                                                 
        Supported RX frame types:                                                                                                                          
                 * IBSS: 0xd0                                                                                                                              
                 * managed: 0x40 0xb0 0xd0                                                                                                                 
                 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0                                                                                                  
                 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0                                                                                             
                 * P2P-client: 0x40 0xd0                                                                                                                   
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0                                                                                              
        WoWLAN support:                                                                                                                                    
                 * wake up on anything (device continues operating normally)                                                                               
        software interface modes (can always be added):                                                                                                    
                 * monitor                                                                                                                                 
        interface combinations are not supported                                                                                                           
        Device supports SAE with AUTHENTICATE command                                                                                                      
        Device supports scan flush.                                                                                                                        
        Supported extended features:`
