### ISSUE TITLE
Make Error in Ubuntu 

### ISSUE THREAD

**Issue by horton4** [aircrack-ng/mdk4#64]
today I was installing Fluxion and it said I needed to install mdk4 which cannot be installed through apt so I cloned this, moved into the directory and ran sudo make and it gave me a page and a half of errors... Error output code from the 'sudo make' command is posted below and if you need any more information please let me know. 

make -C src clean
make[1]: Entering directory `/home/repo/mdk4/src'
rm -f mdk4
rm -f debug.o helpers.o mac_addr.o linkedlist.o greylist.o dumpfile.o packet.o brute.o osdep.o channelhopper.o ghosting.o fragmenting.o
rm -f ../test *.o
make -C osdep clean
make[2]: Entering directory `/home/repo/mdk4/src/osdep'
make -C radiotap clean
make[3]: Entering directory `/home/repo/mdk4/src/osdep/radiotap'
rm -f *.o
make[3]: Leaving directory `/home/repo/mdk4/src/osdep/radiotap'
rm -f libosdep.a  *.o .os.*
make[2]: Leaving directory `/home/repo/mdk4/src/osdep'
make -C attacks clean
make[2]: Entering directory `/home/repo/mdk4/src/attacks'
rm -f attacks.o auth_dos.o beacon_flood.o countermeasures.o deauth.o dummy.o eapol.o fuzzer.o ieee80211s.o probing.o wids.o *.o
make[2]: Leaving directory `/home/repo/mdk4/src/attacks'
make[1]: Leaving directory `/home/repo/mdk4/src'
make -C src
make[1]: Entering directory `/home/repo/mdk4/src'
make -C osdep
make[2]: Entering directory `/home/repo/mdk4/src/osdep'
Building for Linux
make[3]: Entering directory `/home/repo/mdk4/src/osdep'
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o osdep.o osdep.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o network.o network.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o file.o file.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o linux.o linux.c
linux.c:1048:12: warning: ‘linux_set_channel’ defined but not used [-Wunused-function]
 static int linux_set_channel(struct wif *wi, int channel)
            ^
linux.c:2057:13: warning: ‘linux_close’ defined but not used [-Wunused-function]
 static void linux_close(struct wif *wi)
             ^
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o linux_tap.o linux_tap.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o radiotap/radiotap.o radiotap/radiotap.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o common.o common.c
ar cru libosdep.a  osdep.o network.o file.o linux.o linux_tap.o radiotap/radiotap.o common.o
ranlib libosdep.a 
touch .os.Linux
make[3]: Leaving directory `/home/repo/mdk4/src/osdep'
make[2]: Leaving directory `/home/repo/mdk4/src/osdep'
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o debug.o debug.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o helpers.o helpers.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o mac_addr.o mac_addr.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o linkedlist.o linkedlist.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o greylist.o greylist.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o dumpfile.o dumpfile.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o packet.o packet.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o brute.o brute.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o osdep.o osdep.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3   -fstack-protector -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra -fcommon   -c -o channelhopper.o channelhopper.c
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:143:8: error: redefinition of ‘struct ifmap’
 struct ifmap {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:111:8: note: originally defined here
 struct ifmap
        ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:177:8: error: redefinition of ‘struct ifreq’
 struct ifreq {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:126:8: note: originally defined here
 struct ifreq
        ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:226:8: error: redefinition of ‘struct ifconf’
 struct ifconf  {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:176:8: note: originally defined here
 struct ifconf
        ^
channelhopper.c: In function ‘error_handler’:
channelhopper.c:155:46: warning: unused parameter ‘nla’ [-Wunused-parameter]
 static int error_handler(struct sockaddr_nl *nla, struct nlmsgerr *err,
                                              ^
channelhopper.c: In function ‘finish_handler’:
channelhopper.c:163:42: warning: unused parameter ‘msg’ [-Wunused-parameter]
 static int finish_handler(struct nl_msg *msg, void *arg)
                                          ^
channelhopper.c: In function ‘ack_handler’:
channelhopper.c:170:39: warning: unused parameter ‘msg’ [-Wunused-parameter]
 static int ack_handler(struct nl_msg *msg, void *arg)
                                       ^
channelhopper.c: In function ‘valid_handler’:
channelhopper.c:186:45: warning: unused parameter ‘arg’ [-Wunused-parameter]
 int valid_handler(struct nl_msg *msg, void *arg)
                                             ^
channelhopper.c: In function ‘handle_channels’:
channelhopper.c:328:50: warning: unused parameter ‘state’ [-Wunused-parameter]
 static int handle_channels(struct nl80211_state *state, struct nl_msg *msg)
                                                  ^
channelhopper.c: At top level:
channelhopper.c:240:14: warning: ‘dfs_state_name’ defined but not used [-Wunused-function]
 static char *dfs_state_name(enum nl80211_dfs_state state)
              ^
make[1]: *** [channelhopper.o] Error 1
make[1]: Leaving directory `/home/repo/mdk4/src'
make: *** [all] Error 2
REPO>

**Comment by horton4** [comment]
It gives me another page and a half of error if I run `sudo make install`

**Comment by E7mer** [comment]
Which version of Ubuntu？Have you executed this command，apt-get install pkg-config libnl-3-dev libnl-genl-3-dev libpcap-dev ？

**Comment by horton4** [comment]
Ubuntu 4.4.0-148-generic

**Comment by horton4** [comment]
and yes I have all those installed and at the latest version

**Comment by horton4** [comment]
I have also deleted the mdk4 folder and downloaded the latest version from here and it still wouldn't install

**Comment by E7mer** [comment]
I did not reproduce your issue.
I removed the header file if.h in channelhopper.c, you can try again.

**Comment by horton4** [comment]
Ok I just tried installing again. The error changed and its much shorter now (whew)... `radiotap/platform.h:9:11: fatal error: 'endian.h' file not found`

**Comment by horton4** [comment]
is there a dependency I need to install?

**Comment by horton4** [comment]
Ok, just tried it on a different ubuntu system and no errors occurred. Thank you!
