### ISSUE TITLE
Add in Mdk4 mode automatic channel hopping 

### ISSUE THREAD

**Issue by jack1971** [aircrack-ng/mdk4#66]

**Comment by wh0am3y3** [comment]
Do you mean `-c h` ?

**Comment by Zanzaux** [comment]
Hi, yes an automatic channel search so if the access point changes channel it is automatically followed.

**Comment by minanagehsalalma** [comment]
> Hi, yes an automatic channel search so if the access point changes channel it is automatically followed.

It's already there 

it works by not typing the ` -c  ` argument or you type it and don't provide a channel

Just close the Issue already
