### ISSUE TITLE
Block Hidden Cameras

### ISSUE THREAD

**Issue by gitdebpro** [aircrack-ng/mdk4#68]
https://csafetyblogger.wordpress.com/

Have you ever wondered or feel paranoid that someone is recording you obviously beyond your permission via hidden cameras ?

Are you a young woman who often feels insecure or anxious not to try on a newly bought dress because you feel that the changing room might be bugged with hidden cctv cameras ??

Are you some married or unmarried couple who often feel insecure to spent your quality moments or intimate moments inside a hotel room because you think that some pervert has planted a hidden camera to record your intimacy ???

Are you any person whose neighbor is spying on him/her via hidden camera ????

Are you any person other than the above categories who is scared of or want to avoid hidden cameras ?????

If the answer to the above questions is yes then you are on the right path and just follow the instructions mentioned in this blog. I will write this blog and update it with new informations once you provide me with some feedback in the comment section.

**" DISCLAIMER - I am writing this blog for the purpose of avoiding hidden cameras used in illegal manner. I don't promote the use of this information against a legally used cctv camera. Also the information provided here is for educational purpose and under no circumstances I will be held liable as a promoter of illegal activities. Please use the informations provided here at you own risk and never use it in any premises where it has been mentioned that you are under cctv surveillance.

For Example say I have a knife at my home and i use it daily to cut vegetables and fruits. The same knife can be called as a murder weapon only if I have used it for such purpose. One cannot blame me for having a knife at my residence. "
**
So guys and gals lets start the process of fight against all those perverts who think that they are smart enough or cool enough only according to their own capability and the rest of the world is unknown to that pervert mentality.

First of all you should know that most of these cameras are operated wirelessly or via wireless medium like bluetooth or wifi. Now range and speed of wifi is far better than that of bluetooth so whoever is using those cameras are definitely connected via some wifi may be routers or even mobile phones. They are definitely not using hidden cameras with lots of wires seen by the victims right ?

Things you will need to initiate the process are mentioned below :

Laptop.

Wifi Adapter (supporting monitoring mode & frame injection).*

Linux based Operating System (Kali Linux Recommended).**

AIRCRACK-NG, MDK4 (softwares available at github search for it ).

Some basic knowledge of Linux.

* Any wifi adapter which supports monitor mode and packet injection or frame injection will do irrespective of the fact whether its a 2.4Ghz or 5.8Ghz or any antenna size. It could be as low as no external antenna or even 9Dbi antenna. For example you can buy any wifi adapter with realtek, ralink chipset but before buying search enough over the internet whether they support monitor mode and frame injection or not. Rtl8188eus, Rtl8812au, Rtl8188ftv, Rtl8188fu etc. Don't worry these are cheap hardly $5 to $6 respectively.

** You can u any linux like ubuntu, linux mint or any debian based linux but I have mentioned Kali Linux because the tools or softwares AIRCRACK-NG, MDK4 are available at Kali repositories by default and also the driver for RTL8188EUS and RTL8812AU available there. How to install them will discuss later as we move on.

Now we are going to follow some steps in order to achieve what we want. The steps are mentioned below :

Step 1-    Install Ubuntu Linux / Kali Linux.             

                 update it (sudo apt update).

                 upgrade it (sudo apt upgrade).

Step2- Install Linux Kernel Headers (search google for commands).

Step3- Install your respective wifi adapter chipset drivers (search google or github for this and do this before buying one).

Step4- Install AIRCRACK-NG & MDK4 (sudo apt install aircrack-ng mdk4).

Step5- Track the culprit device using Aircrack-ng I mean Airodump-ng (search google or youtube for videos).

Step6- Use MDK4 for disconnecting those illegal hidden cameras. The Command is :

                mdk4 wlan0 f -s a -m n -c h

               mdk4= tool name.

                wlan0= wifi interface name at monitor mode it could be “mon0” or anything else.

                F= Packet Fuzzer (Discussed Below)*

                -s a= Source(s) which is Air(a).

                -m n= Modifiers(m) which is None(n).

                -c h= Channel(c) which is in Hopping(h) mode.

                -c 1= Channel(c) which is at Channel 1.

* What basically you are doing is redirecting the wireless traffic in different direction instead of the host and aclient. For example say there are five router(host) like A, B, C, D & E which are connected to their cameras(client) like a, b, c, d & e respectively. So now what you are doing is redirecting the traffic in between the client and host in such a way that the host is not able to receive data from its respective client, instead its receiving traffic from some different client which is not registered with it. So as a result it will deny or reject the connection.

Lets make it more simple.

Router “A” is registered with Camera “a” ; Router “B” is registered with Camera “b” and so on. Now what you are doing is redirecting traffic of Camera “a” to Router “C” and traffic from Camera “b” to Router “E” and so on. Since the Router is receiving traffic from different camera which is not registered with it, it will reject the connection and this process will go on and on.

In this way we can disconnect those hidden cameras which were planted unethically or illegally. Not only that we can also disconnect anyone using mobile devices to control those hidden cameras.

**Comment by E7mer** [comment]
That's great. You're doing something worthwhile.
