### ISSUE TITLE
Make failed！

### ISSUE THREAD

**Issue by EastwindZL** [aircrack-ng/mdk4#9]
![20180904_161617](https://user-images.githubusercontent.com/29472751/45019069-fb568a80-b05d-11e8-8c48-a689956092cf.png)

**Comment by aircrack-ng** [comment]
post the whole compile log and use code tags from github instead of a picture. The screenshot you posted show `make` failed but it doesn't show why

**Comment by EastwindZL** [comment]
`root@chip:/home/chip/mdk4# sudo make install
make -C src clean
make[1]: Entering directory '/home/chip/mdk4/src'
rm -f mdk4
rm -f debug.o helpers.o mac_addr.o linkedlist.o greylist.o dumpfile.o packet.o brute.o osdep.o channelhopper.o ghosting.o fragmenting.o
rm -f ../test *.o
make -C osdep clean
make[2]: Entering directory '/home/chip/mdk4/src/osdep'
make -C radiotap clean
make[3]: Entering directory '/home/chip/mdk4/src/osdep/radiotap'
rm -f *.o
make[3]: Leaving directory '/home/chip/mdk4/src/osdep/radiotap'
rm -f libosdep.a  *.o .os.*
make[2]: Leaving directory '/home/chip/mdk4/src/osdep'
make -C attacks clean
make[2]: Entering directory '/home/chip/mdk4/src/attacks'
rm -f attacks.o auth_dos.o beacon_flood.o countermeasures.o deauth.o dummy.o eapol.o fuzzer.o ieee80211s.o probing.o wids.o *.o
make[2]: Leaving directory '/home/chip/mdk4/src/attacks'
make[1]: Leaving directory '/home/chip/mdk4/src'
make -C src
make[1]: Entering directory '/home/chip/mdk4/src'
make -C osdep
make[2]: Entering directory '/home/chip/mdk4/src/osdep'
Building for Linux
make[3]: Entering directory '/home/chip/mdk4/src/osdep'
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o osdep.o osdep.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o network.o network.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o file.o file.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o linux.o linux.c
linux.c:1048:12: warning: 'linux_set_channel' defined but not used [-Wunused-function]
 static int linux_set_channel(struct wif *wi, int channel)
            ^
linux.c:2057:13: warning: 'linux_close' defined but not used [-Wunused-function]
 static void linux_close(struct wif *wi)
             ^
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o linux_tap.o linux_tap.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o radiotap/radiotap.o radiotap/radiotap.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o common.o common.c
ar cru libosdep.a  osdep.o network.o file.o linux.o linux_tap.o radiotap/radiotap.o common.o
ranlib libosdep.a 
touch .os.Linux
make[3]: Leaving directory '/home/chip/mdk4/src/osdep'
make[2]: Leaving directory '/home/chip/mdk4/src/osdep'
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o debug.o debug.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o helpers.o helpers.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o mac_addr.o mac_addr.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o linkedlist.o linkedlist.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o greylist.o greylist.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o dumpfile.o dumpfile.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o packet.o packet.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o brute.o brute.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o osdep.o osdep.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o channelhopper.o channelhopper.c
In file included from channelhopper.c:4:0:
/usr/include/linux/if.h:71:2: error: redeclaration of enumerator 'IFF_UP'
  IFF_UP    = 1<<0,  /* sysfs */
  ^
/usr/include/net/if.h:44:5: note: previous definition of 'IFF_UP' was here
     IFF_UP = 0x1,  /* Interface is up.  */
     ^
/usr/include/linux/if.h:72:2: error: redeclaration of enumerator 'IFF_BROADCAST'
  IFF_BROADCAST   = 1<<1,  /* __volatile__ */
  ^
/usr/include/net/if.h:46:5: note: previous definition of 'IFF_BROADCAST' was here
     IFF_BROADCAST = 0x2, /* Broadcast address valid.  */
     ^
/usr/include/linux/if.h:73:2: error: redeclaration of enumerator 'IFF_DEBUG'
  IFF_DEBUG   = 1<<2,  /* sysfs */
  ^
/usr/include/net/if.h:48:5: note: previous definition of 'IFF_DEBUG' was here
     IFF_DEBUG = 0x4,  /* Turn on debugging.  */
     ^
/usr/include/linux/if.h:74:2: error: redeclaration of enumerator 'IFF_LOOPBACK'
  IFF_LOOPBACK   = 1<<3,  /* __volatile__ */
  ^
/usr/include/net/if.h:50:5: note: previous definition of 'IFF_LOOPBACK' was here
     IFF_LOOPBACK = 0x8,  /* Is a loopback net.  */
     ^
/usr/include/linux/if.h:75:2: error: redeclaration of enumerator 'IFF_POINTOPOINT'
  IFF_POINTOPOINT   = 1<<4,  /* __volatile__ */
  ^
/usr/include/net/if.h:52:5: note: previous definition of 'IFF_POINTOPOINT' was here
     IFF_POINTOPOINT = 0x10, /* Interface is point-to-point link.  */
     ^
/usr/include/linux/if.h:76:2: error: redeclaration of enumerator 'IFF_NOTRAILERS'
  IFF_NOTRAILERS   = 1<<5,  /* sysfs */
  ^
/usr/include/net/if.h:54:5: note: previous definition of 'IFF_NOTRAILERS' was here
     IFF_NOTRAILERS = 0x20, /* Avoid use of trailers.  */
     ^
/usr/include/linux/if.h:77:2: error: redeclaration of enumerator 'IFF_RUNNING'
  IFF_RUNNING   = 1<<6,  /* __volatile__ */
  ^
/usr/include/net/if.h:56:5: note: previous definition of 'IFF_RUNNING' was here
     IFF_RUNNING = 0x40,  /* Resources allocated.  */
     ^
/usr/include/linux/if.h:78:2: error: redeclaration of enumerator 'IFF_NOARP'
  IFF_NOARP   = 1<<7,  /* sysfs */
  ^
/usr/include/net/if.h:58:5: note: previous definition of 'IFF_NOARP' was here
     IFF_NOARP = 0x80,  /* No address resolution protocol.  */
     ^
/usr/include/linux/if.h:79:2: error: redeclaration of enumerator 'IFF_PROMISC'
  IFF_PROMISC   = 1<<8,  /* sysfs */
  ^
/usr/include/net/if.h:60:5: note: previous definition of 'IFF_PROMISC' was here
     IFF_PROMISC = 0x100, /* Receive all packets.  */
     ^
/usr/include/linux/if.h:80:2: error: redeclaration of enumerator 'IFF_ALLMULTI'
  IFF_ALLMULTI   = 1<<9,  /* sysfs */
  ^
/usr/include/net/if.h:64:5: note: previous definition of 'IFF_ALLMULTI' was here
     IFF_ALLMULTI = 0x200, /* Receive all multicast packets.  */
     ^
/usr/include/linux/if.h:81:2: error: redeclaration of enumerator 'IFF_MASTER'
  IFF_MASTER   = 1<<10, /* __volatile__ */
  ^
/usr/include/net/if.h:67:5: note: previous definition of 'IFF_MASTER' was here
     IFF_MASTER = 0x400,  /* Master of a load balancer.  */
     ^
/usr/include/linux/if.h:82:2: error: redeclaration of enumerator 'IFF_SLAVE'
  IFF_SLAVE   = 1<<11, /* __volatile__ */
  ^
/usr/include/net/if.h:69:5: note: previous definition of 'IFF_SLAVE' was here
     IFF_SLAVE = 0x800,  /* Slave of a load balancer.  */
     ^
/usr/include/linux/if.h:83:2: error: redeclaration of enumerator 'IFF_MULTICAST'
  IFF_MULTICAST   = 1<<12, /* sysfs */
  ^
/usr/include/net/if.h:72:5: note: previous definition of 'IFF_MULTICAST' was here
     IFF_MULTICAST = 0x1000, /* Supports multicast.  */
     ^
/usr/include/linux/if.h:84:2: error: redeclaration of enumerator 'IFF_PORTSEL'
  IFF_PORTSEL   = 1<<13, /* sysfs */
  ^
/usr/include/net/if.h:75:5: note: previous definition of 'IFF_PORTSEL' was here
     IFF_PORTSEL = 0x2000, /* Can set media type.  */
     ^
/usr/include/linux/if.h:85:2: error: redeclaration of enumerator 'IFF_AUTOMEDIA'
  IFF_AUTOMEDIA   = 1<<14, /* sysfs */
  ^
/usr/include/net/if.h:77:5: note: previous definition of 'IFF_AUTOMEDIA' was here
     IFF_AUTOMEDIA = 0x4000, /* Auto media select active.  */
     ^
/usr/include/linux/if.h:86:2: error: redeclaration of enumerator 'IFF_DYNAMIC'
  IFF_DYNAMIC   = 1<<15, /* sysfs */
  ^
/usr/include/net/if.h:79:5: note: previous definition of 'IFF_DYNAMIC' was here
     IFF_DYNAMIC = 0x8000 /* Dialup device with changing addresses.  */
     ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:169:8: error: redefinition of 'struct ifmap'
 struct ifmap {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:111:8: note: originally defined here
 struct ifmap
        ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:203:8: error: redefinition of 'struct ifreq'
 struct ifreq {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:126:8: note: originally defined here
 struct ifreq
        ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:252:8: error: redefinition of 'struct ifconf'
 struct ifconf  {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:176:8: note: originally defined here
 struct ifconf
        ^
channelhopper.c: In function 'error_handler':
channelhopper.c:155:46: warning: unused parameter 'nla' [-Wunused-parameter]
 static int error_handler(struct sockaddr_nl *nla, struct nlmsgerr *err,
                                              ^
channelhopper.c: In function 'finish_handler':
channelhopper.c:163:42: warning: unused parameter 'msg' [-Wunused-parameter]
 static int finish_handler(struct nl_msg *msg, void *arg)
                                          ^
channelhopper.c: In function 'ack_handler':
channelhopper.c:170:39: warning: unused parameter 'msg' [-Wunused-parameter]
 static int ack_handler(struct nl_msg *msg, void *arg)
                                       ^
channelhopper.c: In function 'valid_handler':
channelhopper.c:186:45: warning: unused parameter 'arg' [-Wunused-parameter]
 int valid_handler(struct nl_msg *msg, void *arg)
                                             ^
channelhopper.c: In function 'handle_channels':
channelhopper.c:328:50: warning: unused parameter 'state' [-Wunused-parameter]
 static int handle_channels(struct nl80211_state *state, struct nl_msg *msg)
                                                  ^
channelhopper.c: In function 'channel_sniff':
channelhopper.c:387:6: warning: unused variable 'ie_type' [-Wunused-variable]
  int ie_type;
      ^
channelhopper.c: In function 'init_channel_hopper':
channelhopper.c:592:19: warning: unused variable 'i' [-Wunused-variable]
     int lpos = 0, i;
                   ^
channelhopper.c: At top level:
channelhopper.c:240:14: warning: 'dfs_state_name' defined but not used [-Wunused-function]
 static char *dfs_state_name(enum nl80211_dfs_state state)
              ^
<builtin>: recipe for target 'channelhopper.o' failed
make[1]: *** [channelhopper.o] Error 1
make[1]: Leaving directory '/home/chip/mdk4/src'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by EastwindZL** [comment]
``root@chip:/home/chip/mdk4# sudo make install
make -C src clean
make[1]: Entering directory '/home/chip/mdk4/src'
rm -f mdk4
rm -f debug.o helpers.o mac_addr.o linkedlist.o greylist.o dumpfile.o packet.o brute.o osdep.o channelhopper.o ghosting.o fragmenting.o
rm -f ../test *.o
make -C osdep clean
make[2]: Entering directory '/home/chip/mdk4/src/osdep'
make -C radiotap clean
make[3]: Entering directory '/home/chip/mdk4/src/osdep/radiotap'
rm -f *.o
make[3]: Leaving directory '/home/chip/mdk4/src/osdep/radiotap'
rm -f libosdep.a  *.o .os.*
make[2]: Leaving directory '/home/chip/mdk4/src/osdep'
make -C attacks clean
make[2]: Entering directory '/home/chip/mdk4/src/attacks'
rm -f attacks.o auth_dos.o beacon_flood.o countermeasures.o deauth.o dummy.o eapol.o fuzzer.o ieee80211s.o probing.o wids.o *.o
make[2]: Leaving directory '/home/chip/mdk4/src/attacks'
make[1]: Leaving directory '/home/chip/mdk4/src'
make -C src
make[1]: Entering directory '/home/chip/mdk4/src'
make -C osdep
make[2]: Entering directory '/home/chip/mdk4/src/osdep'
Building for Linux
make[3]: Entering directory '/home/chip/mdk4/src/osdep'
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o osdep.o osdep.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o network.o network.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o file.o file.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o linux.o linux.c
linux.c:1048:12: warning: 'linux_set_channel' defined but not used [-Wunused-function]
 static int linux_set_channel(struct wif *wi, int channel)
            ^
linux.c:2057:13: warning: 'linux_close' defined but not used [-Wunused-function]
 static void linux_close(struct wif *wi)
             ^
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o linux_tap.o linux_tap.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o radiotap/radiotap.o radiotap/radiotap.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -fPIC -I..    -c -o common.o common.c
ar cru libosdep.a  osdep.o network.o file.o linux.o linux_tap.o radiotap/radiotap.o common.o
ranlib libosdep.a 
touch .os.Linux
make[3]: Leaving directory '/home/chip/mdk4/src/osdep'
make[2]: Leaving directory '/home/chip/mdk4/src/osdep'
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o debug.o debug.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o helpers.o helpers.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o mac_addr.o mac_addr.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o linkedlist.o linkedlist.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o greylist.o greylist.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o dumpfile.o dumpfile.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o packet.o packet.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o brute.o brute.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o osdep.o osdep.c
gcc -g -W -Wall -O3 -D_FILE_OFFSET_BITS=64 -D_REVISION=mdk4-v1  -DCONFIG_LIBNL30 -DCONFIG_LIBNL -I/usr/include/libnl3  -fstack-protector-strong -Wno-unused-but-set-variable -Wno-array-bounds -g -O3 -Wall -Wextra    -c -o channelhopper.o channelhopper.c
In file included from channelhopper.c:4:0:
/usr/include/linux/if.h:71:2: error: redeclaration of enumerator 'IFF_UP'
  IFF_UP    = 1<<0,  /* sysfs */
  ^
/usr/include/net/if.h:44:5: note: previous definition of 'IFF_UP' was here
     IFF_UP = 0x1,  /* Interface is up.  */
     ^
/usr/include/linux/if.h:72:2: error: redeclaration of enumerator 'IFF_BROADCAST'
  IFF_BROADCAST   = 1<<1,  /* __volatile__ */
  ^
/usr/include/net/if.h:46:5: note: previous definition of 'IFF_BROADCAST' was here
     IFF_BROADCAST = 0x2, /* Broadcast address valid.  */
     ^
/usr/include/linux/if.h:73:2: error: redeclaration of enumerator 'IFF_DEBUG'
  IFF_DEBUG   = 1<<2,  /* sysfs */
  ^
/usr/include/net/if.h:48:5: note: previous definition of 'IFF_DEBUG' was here
     IFF_DEBUG = 0x4,  /* Turn on debugging.  */
     ^
/usr/include/linux/if.h:74:2: error: redeclaration of enumerator 'IFF_LOOPBACK'
  IFF_LOOPBACK   = 1<<3,  /* __volatile__ */
  ^
/usr/include/net/if.h:50:5: note: previous definition of 'IFF_LOOPBACK' was here
     IFF_LOOPBACK = 0x8,  /* Is a loopback net.  */
     ^
/usr/include/linux/if.h:75:2: error: redeclaration of enumerator 'IFF_POINTOPOINT'
  IFF_POINTOPOINT   = 1<<4,  /* __volatile__ */
  ^
/usr/include/net/if.h:52:5: note: previous definition of 'IFF_POINTOPOINT' was here
     IFF_POINTOPOINT = 0x10, /* Interface is point-to-point link.  */
     ^
/usr/include/linux/if.h:76:2: error: redeclaration of enumerator 'IFF_NOTRAILERS'
  IFF_NOTRAILERS   = 1<<5,  /* sysfs */
  ^
/usr/include/net/if.h:54:5: note: previous definition of 'IFF_NOTRAILERS' was here
     IFF_NOTRAILERS = 0x20, /* Avoid use of trailers.  */
     ^
/usr/include/linux/if.h:77:2: error: redeclaration of enumerator 'IFF_RUNNING'
  IFF_RUNNING   = 1<<6,  /* __volatile__ */
  ^
/usr/include/net/if.h:56:5: note: previous definition of 'IFF_RUNNING' was here
     IFF_RUNNING = 0x40,  /* Resources allocated.  */
     ^
/usr/include/linux/if.h:78:2: error: redeclaration of enumerator 'IFF_NOARP'
  IFF_NOARP   = 1<<7,  /* sysfs */
  ^
/usr/include/net/if.h:58:5: note: previous definition of 'IFF_NOARP' was here
     IFF_NOARP = 0x80,  /* No address resolution protocol.  */
     ^
/usr/include/linux/if.h:79:2: error: redeclaration of enumerator 'IFF_PROMISC'
  IFF_PROMISC   = 1<<8,  /* sysfs */
  ^
/usr/include/net/if.h:60:5: note: previous definition of 'IFF_PROMISC' was here
     IFF_PROMISC = 0x100, /* Receive all packets.  */
     ^
/usr/include/linux/if.h:80:2: error: redeclaration of enumerator 'IFF_ALLMULTI'
  IFF_ALLMULTI   = 1<<9,  /* sysfs */
  ^
/usr/include/net/if.h:64:5: note: previous definition of 'IFF_ALLMULTI' was here
     IFF_ALLMULTI = 0x200, /* Receive all multicast packets.  */
     ^
/usr/include/linux/if.h:81:2: error: redeclaration of enumerator 'IFF_MASTER'
  IFF_MASTER   = 1<<10, /* __volatile__ */
  ^
/usr/include/net/if.h:67:5: note: previous definition of 'IFF_MASTER' was here
     IFF_MASTER = 0x400,  /* Master of a load balancer.  */
     ^
/usr/include/linux/if.h:82:2: error: redeclaration of enumerator 'IFF_SLAVE'
  IFF_SLAVE   = 1<<11, /* __volatile__ */
  ^
/usr/include/net/if.h:69:5: note: previous definition of 'IFF_SLAVE' was here
     IFF_SLAVE = 0x800,  /* Slave of a load balancer.  */
     ^
/usr/include/linux/if.h:83:2: error: redeclaration of enumerator 'IFF_MULTICAST'
  IFF_MULTICAST   = 1<<12, /* sysfs */
  ^
/usr/include/net/if.h:72:5: note: previous definition of 'IFF_MULTICAST' was here
     IFF_MULTICAST = 0x1000, /* Supports multicast.  */
     ^
/usr/include/linux/if.h:84:2: error: redeclaration of enumerator 'IFF_PORTSEL'
  IFF_PORTSEL   = 1<<13, /* sysfs */
  ^
/usr/include/net/if.h:75:5: note: previous definition of 'IFF_PORTSEL' was here
     IFF_PORTSEL = 0x2000, /* Can set media type.  */
     ^
/usr/include/linux/if.h:85:2: error: redeclaration of enumerator 'IFF_AUTOMEDIA'
  IFF_AUTOMEDIA   = 1<<14, /* sysfs */
  ^
/usr/include/net/if.h:77:5: note: previous definition of 'IFF_AUTOMEDIA' was here
     IFF_AUTOMEDIA = 0x4000, /* Auto media select active.  */
     ^
/usr/include/linux/if.h:86:2: error: redeclaration of enumerator 'IFF_DYNAMIC'
  IFF_DYNAMIC   = 1<<15, /* sysfs */
  ^
/usr/include/net/if.h:79:5: note: previous definition of 'IFF_DYNAMIC' was here
     IFF_DYNAMIC = 0x8000 /* Dialup device with changing addresses.  */
     ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:169:8: error: redefinition of 'struct ifmap'
 struct ifmap {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:111:8: note: originally defined here
 struct ifmap
        ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:203:8: error: redefinition of 'struct ifreq'
 struct ifreq {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:126:8: note: originally defined here
 struct ifreq
        ^
In file included from /usr/include/linux/wireless.h:74:0,
                 from channelhopper.c:13:
/usr/include/linux/if.h:252:8: error: redefinition of 'struct ifconf'
 struct ifconf  {
        ^
In file included from channelhopper.c:4:0:
/usr/include/net/if.h:176:8: note: originally defined here
 struct ifconf
        ^
channelhopper.c: In function 'error_handler':
channelhopper.c:155:46: warning: unused parameter 'nla' [-Wunused-parameter]
 static int error_handler(struct sockaddr_nl *nla, struct nlmsgerr *err,
                                              ^
channelhopper.c: In function 'finish_handler':
channelhopper.c:163:42: warning: unused parameter 'msg' [-Wunused-parameter]
 static int finish_handler(struct nl_msg *msg, void *arg)
                                          ^
channelhopper.c: In function 'ack_handler':
channelhopper.c:170:39: warning: unused parameter 'msg' [-Wunused-parameter]
 static int ack_handler(struct nl_msg *msg, void *arg)
                                       ^
channelhopper.c: In function 'valid_handler':
channelhopper.c:186:45: warning: unused parameter 'arg' [-Wunused-parameter]
 int valid_handler(struct nl_msg *msg, void *arg)
                                             ^
channelhopper.c: In function 'handle_channels':
channelhopper.c:328:50: warning: unused parameter 'state' [-Wunused-parameter]
 static int handle_channels(struct nl80211_state *state, struct nl_msg *msg)
                                                  ^
channelhopper.c: In function 'channel_sniff':
channelhopper.c:387:6: warning: unused variable 'ie_type' [-Wunused-variable]
  int ie_type;
      ^
channelhopper.c: In function 'init_channel_hopper':
channelhopper.c:592:19: warning: unused variable 'i' [-Wunused-variable]
     int lpos = 0, i;
                   ^
channelhopper.c: At top level:
channelhopper.c:240:14: warning: 'dfs_state_name' defined but not used [-Wunused-function]
 static char *dfs_state_name(enum nl80211_dfs_state state)
              ^
<builtin>: recipe for target 'channelhopper.o' failed
make[1]: *** [channelhopper.o] Error 1
make[1]: Leaving directory '/home/chip/mdk4/src'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2
